import { useEffect, useState } from 'react'
import type { GraphEntity, ViewPreferences, VirtualGroup } from '../../types/v1'
const colors = ['lime','blue','violet','amber'] as const
interface Props {entities:GraphEntity[]; preferences:ViewPreferences; save(preferences:ViewPreferences):Promise<void>; focus(id:string):void}
function Members({entities,labels,members,setMembers}: {entities:GraphEntity[]; labels:Record<string,string>; members:string[]; setMembers(ids:string[]):void}) {
  const [query,setQuery] = useState(''); const [limit,setLimit] = useState(100)
  const options = entities.filter(e => `${e.path} ${labels[e.id] ?? e.label}`.toLowerCase().includes(query.toLowerCase()))
  return <div className="group-members"><label>Find group members<input value={query} onChange={e => {setQuery(e.target.value); setLimit(100)}} placeholder="Search the complete file and folder inventory"/></label><p>{members.length} selected · grouping does not move source files</p><div className="member-options">{options.slice(0,limit).map(e => <label key={e.id} title={e.path}><input type="checkbox" checked={members.includes(e.id)} disabled={!members.includes(e.id) && members.length >= 500} onChange={() => setMembers(members.includes(e.id) ? members.filter(id => id !== e.id) : [...members,e.id])}/>{labels[e.id] ?? e.path ?? e.label}</label>)}</div>{options.length > limit && <button type="button" className="btn small" onClick={() => setLimit(limit+100)}>Show more members</button>}</div>
}
function GroupForm({group,entities,preferences,save}: Omit<Props,'focus'> & {group:VirtualGroup}) {
  const [label,setLabel] = useState(group.label); const [color,setColor] = useState(group.color ?? 'lime'); const [members,setMembers] = useState(group.members)
  const [busy,setBusy] = useState(false); const [error,setError] = useState(''); const [saved,setSaved] = useState(false)
  useEffect(() => {setLabel(group.label); setColor(group.color ?? 'lime'); setMembers(group.members)}, [group])
  return <form className="group-edit-form" onSubmit={async e => {e.preventDefault(); setBusy(true); setError(''); setSaved(false); try {const labels={...preferences.labels}; delete labels[group.id]; await save({...preferences,labels,groups:preferences.groups.map(g => g.id === group.id ? {...g,label:label.trim(),color,members} : g)}); setSaved(true)} catch(e) {setError(e instanceof Error ? e.message : 'Unable to save group.')} finally {setBusy(false)}}}>
    <label>Group name<input value={label} maxLength={60} required onChange={e => {setLabel(e.target.value);setSaved(false)}}/></label><label>Group color<select aria-label="Group color" value={color} onChange={e => {setColor(e.target.value as typeof color);setSaved(false)}}>{colors.map(c => <option key={c}>{c}</option>)}</select></label>
    <Members entities={entities} labels={preferences.labels} members={members} setMembers={ids => {setMembers(ids);setSaved(false)}}/>
    <button className="btn small" disabled={busy || !label.trim()}>Save group</button>{saved && <p role="status">Group saved.</p>}{error && <p role="alert">{error}</p>}
  </form>
}
export function GroupEditor({entities,preferences,save,focus}:Props) {
  const [name,setName] = useState(''); const [members,setMembers] = useState<string[]>([]); const [busy,setBusy] = useState(false); const [error,setError] = useState('')
  return <section className="group-editor" aria-label="Virtual groups"><h3>Virtual groups</h3><form onSubmit={async e => {e.preventDefault(); setBusy(true);setError('');try {await save({...preferences,groups:[...preferences.groups,{id:'group_'+crypto.randomUUID(),label:name.trim(),members,color:'lime'}]});setName('');setMembers([])}catch(e){setError(e instanceof Error ? e.message : 'Unable to create group.')}finally{setBusy(false)}}}>
    <label>New virtual group<input value={name} maxLength={60} onChange={e => setName(e.target.value)} placeholder="e.g. Upload workflow"/></label><Members entities={entities} labels={preferences.labels} members={members} setMembers={setMembers}/><button className="btn small" disabled={busy || !name.trim() || !members.length || preferences.groups.length >= 30}>Create group from selected members</button>
  </form>{preferences.groups.map(group => <div className="group-card" key={group.id}><div className="group-row"><span className={`group-swatch group-${group.color ?? 'lime'}`} aria-label={`${group.color ?? 'lime'} group`}/><button className="btn small" onClick={() => focus(group.id)}>{group.label} · {group.members.length}</button><button className="btn small" disabled={busy} aria-label={`Remove group ${group.label}`} onClick={async () => {setBusy(true);setError('');try {const labels={...preferences.labels};delete labels[group.id];await save({...preferences,labels,focus:preferences.focus === group.id ? '.' : preferences.focus,groups:preferences.groups.filter(g => g.id !== group.id)});focus('.')}catch(e){setError(e instanceof Error ? e.message : 'Unable to remove group.')}finally{setBusy(false)}}}>Remove</button></div><details><summary>Edit group {group.label}</summary><GroupForm group={group} entities={entities} preferences={preferences} save={save}/></details></div>)}{error && <p role="alert" className="alert error">{error}</p>}</section>
}
