import { test, expect } from '@playwright/test'
import { execFileSync } from 'node:child_process'
import { resolve } from 'node:path'
import { mkdirSync } from 'node:fs'
mkdirSync(resolve(process.env.CODECANOPY_EVIDENCE_DIR ?? 'test-results/browser-evidence'),{recursive:true})
const fixture=resolve('node_modules/.cache/grepo-e2e/ui-completion.zip')
execFileSync(process.env.PYTHON ?? (process.platform === 'win32' ? 'python' : 'python3'),['-c',`import zipfile,sys
from pathlib import Path
Path(sys.argv[1]).parent.mkdir(parents=True, exist_ok=True)
with zipfile.ZipFile(sys.argv[1],'w') as z:
 z.writestr('README.md','# UI verification fixture')
 for i in range(20): z.writestr(f'src/file{i:03}.txt',f'Synthetic content {i}')
`,fixture])
test('map history, adaptive density, editable groups and recent imports',async({page})=>{
  await page.goto('/')
  await page.getByRole('button',{name:'Upload ZIP',exact:true}).click()
  await page.getByLabel('Repository ZIP archive').setInputFiles(fixture)
  await page.getByRole('button',{name:'Explore repository',exact:true}).click()
  await page.waitForURL(/\/overview$/)
  const base=page.url().replace(/\/overview$/,'')
  await page.locator('.overview-folders').getByRole('button',{name:/src/}).click()
  await expect(page.locator('.map-paging')).toContainText('1–8 of 20')
  await page.getByRole('button',{name:'Zoom in',exact:true}).click()
  const svg=page.frameLocator('iframe[title="Repository structure map"]').locator('.diagram-container > svg')
  await expect(svg).toHaveAttribute('data-view-scale','1.25')
  // Deliberately pan toward an edge, where a clamped visible rectangle loses camera position.
  await svg.evaluate(el => {
    const view=(el.ownerDocument.defaultView as unknown as {Archify:{view:{centerAt(x:number,y:number,options:object):void}}}).Archify.view
    view.centerAt(650,260,{scale:1.25,instant:true})
  })
  const cameraTransform=await svg.evaluate(el=>(el as SVGElement).style.transform)
  await page.getByRole('link',{name:'Overview',exact:true}).click()
  await page.goBack()
  await expect(page.locator('.map-breadcrumb')).toContainText('src')
  await expect.poll(()=>svg.evaluate(el=>(el as SVGElement).style.transform)).toBe(cameraTransform)
  await expect(svg).toHaveAttribute('data-view-scale','1.25')
  await page.locator('.map-paging').getByRole('button',{name:'Next',exact:true}).click()
  await expect(page.locator('.map-paging')).toContainText('9–16 of 20')
  await page.goBack()
  await expect(page.locator('.map-paging')).toContainText('1–8 of 20')
  await expect(svg).toHaveAttribute('data-view-scale','1.25')
  await page.getByText('Customize view',{exact:false}).click()
  await page.getByLabel('Map density').selectOption('comfortable')
  await expect(page.locator('.map-paging')).toContainText('1–3 of 20')
  await page.getByLabel('Map density').selectOption('expanded')
  await expect(page.locator('.map-paging')).toContainText('1–8 of 20')
  await page.getByLabel('New virtual group').fill('Reading list')
  await page.getByRole('checkbox',{name:'src/file000.txt',exact:true}).check()
  await page.getByRole('checkbox',{name:'src/file001.txt',exact:true}).check()
  await page.getByRole('button',{name:'Create group from selected members'}).click()
  await page.getByText('Edit group Reading list',{exact:true}).click()
  const editor=page.locator('.group-edit-form')
  await editor.getByLabel('Group name',{exact:true}).fill('Reviewed files')
  await editor.getByLabel('Group color',{exact:true}).selectOption('blue')
  await editor.getByRole('checkbox',{name:'src/file000.txt',exact:true}).uncheck()
  await editor.getByRole('button',{name:'Save group',exact:true}).click()
  await expect(page.getByRole('button',{name:'Reviewed files · 1',exact:true})).toBeVisible()
  await page.reload()
  await page.getByText('Customize view',{exact:false}).click()
  await expect(page.getByRole('button',{name:'Reviewed files · 1',exact:true})).toBeVisible()
  await page.getByText('Edit group Reviewed files',{exact:true}).click()
  await expect(editor.getByLabel('Group color',{exact:true})).toHaveValue('blue')
  await expect(editor.getByRole('checkbox',{name:'src/file000.txt',exact:true})).not.toBeChecked()
  await page.getByRole('button',{name:'Reviewed files · 1',exact:true}).click()
  await expect(page.locator('.map-breadcrumb')).toContainText('Reviewed files')
  await page.getByText('Customize view',{exact:false}).click()
  await expect(page.getByRole('button',{name:'Export HTML',exact:true})).toBeEnabled()
  await expect(svg).toBeVisible()
  await page.screenshot({path:resolve(process.env.CODECANOPY_EVIDENCE_DIR ?? 'test-results/browser-evidence','group-map.png')})
  await page.goto(base+'/map?focus=src&page=0')
  await expect(page.locator('.map-paging')).toContainText('1–8 of 20')
  await page.screenshot({path:resolve(process.env.CODECANOPY_EVIDENCE_DIR ?? 'test-results/browser-evidence','expanded-map.png')})
  const downloadPromise=page.waitForEvent('download')
  await page.getByRole('button',{name:'Export HTML',exact:true}).click()
  await (await downloadPromise).saveAs(resolve(process.env.CODECANOPY_EVIDENCE_DIR ?? 'test-results/browser-evidence','expanded-export.html'))
  await page.getByText('Customize view',{exact:false}).click()
  await page.getByLabel('Map density').selectOption('auto')
  await page.getByText('Customize view',{exact:false}).click()
  await page.setViewportSize({width:390,height:844})
  await expect(page.locator('.map-paging')).toContainText('1–3 of 20')
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:resolve(process.env.CODECANOPY_EVIDENCE_DIR ?? 'test-results/browser-evidence','map-auto-mobile.png')})
  await page.goto('/')
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:resolve(process.env.CODECANOPY_EVIDENCE_DIR ?? 'test-results/browser-evidence','import-mobile.png')})
  const recent=page.getByRole('region',{name:'Recent imports'})
  await expect(recent.getByRole('link',{name:'ui-completion',exact:true})).toBeVisible()
  await expect(recent).toContainText('Structure ready')
  await recent.getByRole('link',{name:'ui-completion',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Start with the structure.'})).toBeVisible()
})

test('GitHub branch submission, failure recovery, ZIP validation and cancellation',async({page})=>{
  let posted:unknown
  await page.route('**/api/v1/imports/github',async route=>{posted=route.request().postDataJSON();await route.fulfill({status:202,json:{run_id:'fixture-run',project_id:'fixture',status:'accepted'}})})
  await page.route('**/api/v1/runs/fixture-run',route=>route.fulfill({json:{id:'fixture-run',status:'failed',diagnostics:[{message:'Fixture: selected branch does not exist.'}]}}))
  await page.goto('/')
  await page.getByLabel('GitHub repository URL').fill('https://github.com/example/project')
  await page.getByText('Branch or tag (optional)',{exact:true}).click()
  await page.getByLabel('Branch, tag, or commit').fill('feature/demo')
  await page.getByRole('button',{name:'Explore repository',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('selected branch does not exist')
  expect(posted).toEqual({url:'https://github.com/example/project',ref:'feature/demo'})
  await expect(page.getByLabel('GitHub repository URL')).toHaveValue('https://github.com/example/project')
  await page.unroute('**/api/v1/runs/fixture-run')
  let cancelled=false
  await page.route('**/api/v1/runs/fixture-run',route=>route.fulfill({json:{id:'fixture-run',status:cancelled?'cancelled':'running',stage:'fetching',diagnostics:[]}}))
  await page.route('**/api/v1/runs/fixture-run/cancel',route=>{expect(route.request().method()).toBe('POST');cancelled=true;return route.fulfill({json:{id:'fixture-run',status:'cancelled',diagnostics:[]}})})
  await page.getByLabel('Branch, tag, or commit').clear()
  await page.getByRole('button',{name:'Explore repository',exact:true}).click()
  await page.getByRole('button',{name:'Cancel import',exact:true}).click()
  await expect(page.getByText('Import cancelled. You can start another import.')).toBeVisible()
  expect(posted).toEqual({url:'https://github.com/example/project'})
  await page.getByRole('button',{name:'Upload ZIP',exact:true}).click()
  await page.getByLabel('Repository ZIP archive').setInputFiles({name:'not-a-zip.txt',mimeType:'text/plain',buffer:Buffer.from('fixture')})
  await page.getByRole('button',{name:'Explore repository',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('Choose a ZIP archive')
})
