import { test, expect } from '@playwright/test'
import { execFileSync } from 'node:child_process'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { createHash } from 'node:crypto'
const evidence = resolve('../bob_sessions/browser-evidence')
mkdirSync(evidence,{recursive:true})
const fixture = resolve('../bob_sessions/verification-fixture.zip')
execFileSync('python3',['../scripts/make_test_zip.py',fixture])
const sizes = [[1672,941],[1440,900],[1920,1080],[1600,1000],[2048,1320]]
test('ZIP workspace, source, organization, deferred slots and offline export', async ({page,browser}) => {
  const errors: string[] = []; page.on('pageerror',error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('link',{name:'CodeCanopy',exact:true})).toBeVisible()
  for (const [width,height] of sizes) {await page.setViewportSize({width,height}); await page.screenshot({path:`${evidence}/import-${width}.png`}); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)}
  await page.setViewportSize({width:1672,height:941})
  await page.getByRole('button',{name:'Upload ZIP',exact:true}).click()
  await page.getByLabel('Repository archive').setInputFiles(fixture)
  await page.getByRole('button',{name:'Explore repository',exact:true}).click()
  await page.waitForURL(/\/overview$/)
  await expect(page.getByRole('button',{name:'Export HTML',exact:true})).toBeEnabled({timeout:40000})
  const workspace = page.url().replace(/\/overview$/,'')
  const iframe = page.frameLocator('iframe[title="Repository structure map"]')
  await expect(iframe.locator('[data-node-id]').first()).toBeVisible()
  const selectedNode = iframe.locator('[data-node-id]').nth(1)
  const selectedId = (await selectedNode.getAttribute('data-node-id'))!.slice(2)
  await selectedNode.click()
  await expect(page.locator(`[data-entity="${selectedId}"]`)).toHaveAttribute('aria-selected','true')
  await page.getByRole('button',{name:'Reset',exact:true}).click()
  for (const [width,height] of sizes) {await page.setViewportSize({width,height}); await page.screenshot({path:`${evidence}/workspace-${width}.png`}); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)}
  await page.setViewportSize({width:1672,height:941})
  await page.getByRole('textbox',{name:'Search repository files',exact:true}).fill('src/main.py')
  await page.getByRole('treeitem',{name:'src/main.py',exact:true}).click()
  await expect(page.getByRole('region',{name:'Source: src/main.py',exact:true})).toBeVisible()
  await expect(page.getByText('value_200 = 200',{exact:true})).toBeVisible()
  await page.locator('.source-paging').getByRole('button',{name:'Next',exact:true}).click()
  await expect(page.getByText('value_201 = 201',{exact:true})).toBeVisible()
  await page.getByLabel('Line',{exact:true}).fill('350'); await page.getByRole('button',{name:'Go',exact:true}).click()
  await expect(page.getByText('value_350 = 350',{exact:true})).toBeVisible()
  await page.getByRole('textbox',{name:'Search repository files',exact:true}).fill('unknown.custom')
  await page.getByRole('treeitem',{name:'src/unknown.custom',exact:true}).click()
  await expect(page.getByText('Safe unknown-language text.',{exact:true})).toBeVisible()
  expect(await page.evaluate(() => 'sourceExecuted' in globalThis)).toBe(false)
  await page.getByText('Customize view',{exact:false}).click()
  await page.getByLabel('Selected entity label',{exact:true}).fill('Reading entry')
  await page.getByRole('button',{name:'Save label',exact:true}).click()
  await expect(page.locator('.entity-button').filter({hasText:'Reading entry'})).toBeVisible()
  await page.getByLabel('New virtual group',{exact:true}).fill('Review group')
  await page.getByRole('checkbox',{name:'Reading entry',exact:true}).check()
  await page.getByRole('button',{name:'Create group from selected members',exact:true}).click()
  await expect(page.getByRole('button',{name:'Review group · 1',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Review group · 1',exact:true}).click()
  await expect(page.locator('.map-breadcrumb')).toContainText('Review group')
  await expect(page.getByRole('button',{name:'Export HTML',exact:true})).toBeEnabled()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button',{name:'Export HTML',exact:true}).click()
  const download = await downloadPromise; const exported = `${evidence}/structural-export.html`; await download.saveAs(exported)
  await page.reload(); await page.getByText('Customize view',{exact:false}).click()
  await expect(page.getByRole('button',{name:'Review group · 1',exact:true})).toBeVisible()
  const deferredRequests: string[] = []
  page.on('request',request => {if (new URL(request.url()).pathname.startsWith('/api/') && /\/(summaries|dependencies|findings|answers|ask|proposals)(?:\/|$)/.test(new URL(request.url()).pathname)) deferredRequests.push(request.url())})
  for (const route of ['dependencies','opportunities/reuse','opportunities/duplicates','opportunities/unused','ask','proposals','docs']) {
    await page.goto(workspace + '/' + route)
    await expect(page.locator('main').getByText('Not connected',{exact:true})).toBeVisible()
    if (route === 'dependencies') await page.screenshot({path:`${evidence}/dependencies-1672.png`})
  }
  expect(deferredRequests).toEqual([])
  await page.goto(workspace + '/map'); await expect(page.getByRole('button',{name:'Export HTML',exact:true})).toBeEnabled()
  await page.setViewportSize({width:390,height:844})
  await page.getByRole('button',{name:'Files',exact:true}).click()
  await expect(page.getByRole('textbox',{name:'Search repository files',exact:true})).toBeVisible()
  await page.getByRole('textbox',{name:'Search repository files',exact:true}).fill('README')
  await page.getByRole('treeitem',{name:'README.md',exact:true}).click()
  await page.getByRole('button',{name:'Context',exact:true}).click()
  await expect(page.getByRole('region',{name:'Source: README.md',exact:true})).toBeVisible()
  await page.screenshot({path:`${evidence}/source-mobile.png`})
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.keyboard.press('Escape')
  await page.setViewportSize({width:1672,height:941})
  await page.keyboard.press('Control+k')
  await expect(page.getByRole('textbox',{name:'Search repository files',exact:true})).toBeFocused()
  const offline = await browser.newContext({offline:true,viewport:{width:1440,height:900}})
  const reader = await offline.newPage(); const network: string[] = []; reader.on('request',r => {if (r.url().startsWith('http')) network.push(r.url())})
  await reader.goto('file://' + exported)
  const provenance = reader.locator('.header .codecanopy-provenance')
  await expect(provenance).toBeVisible()
  await expect(provenance).toContainText('source code not included')
  await expect(reader.locator('[data-node-id]').first()).toBeVisible()
  await reader.locator('[data-node-id]').first().click()
  await expect(reader.locator('.focus-chip')).toBeVisible()
  await reader.locator('#btn-theme').click()
  await reader.screenshot({path:`${evidence}/offline-export-dark.png`})
  await reader.evaluate(() => localStorage.removeItem('archify-theme'))
  await reader.goto('file://' + exported + '?theme=dark')
  await expect(reader.locator('html')).toHaveAttribute('data-theme','dark')
  expect(network).toEqual([])
  expect(errors).toEqual([])
  writeFileSync(`${evidence}/result.json`,JSON.stringify({fixture_only:true,workspace,screen_sizes:sizes,offline_network_requests:network,console_errors:errors,export_sha256:createHash('sha256').update(readFileSync(exported)).digest('hex')},null,2))
  await offline.close()
})
